# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GetJwt < Formula
  desc "A helper utility to make it easier to get a JWT"
  homepage "https://github.com/dbirks/get-jwt"
  version "0.1.0"
  license "Apache2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dbirks/get-jwt/releases/download/v0.1.0/get-jwt_0.1.0_darwin_arm64.tar.gz"
      sha256 "b8e79f9c4bf208b256b24b7bde460061907c38a536d079109e66a6103a045921"

      def install
        bin.install "get-jwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbirks/get-jwt/releases/download/v0.1.0/get-jwt_0.1.0_darwin_amd64.tar.gz"
      sha256 "40b7de633652e49bee4cc07891de08387ed38d4f3b18e95cd9aecbe254e3a5a1"

      def install
        bin.install "get-jwt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbirks/get-jwt/releases/download/v0.1.0/get-jwt_0.1.0_linux_arm64.tar.gz"
      sha256 "a2de1a9f1db547740d0c3855a8e0afd318bd046f7e507b10d3f9d57632904b4d"

      def install
        bin.install "get-jwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbirks/get-jwt/releases/download/v0.1.0/get-jwt_0.1.0_linux_amd64.tar.gz"
      sha256 "ad8c077364ff248458374c6e11f73772797723f9c9003b78dc9756644db32596"

      def install
        bin.install "get-jwt"
      end
    end
  end
end
