# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GetJwt < Formula
  desc "A helper utility to make it easier to get a JWT"
  homepage "https://github.com/dbirks/get-jwt"
  version "0.1.1"
  license "Apache2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbirks/get-jwt/releases/download/v0.1.1/get-jwt_0.1.1_darwin_amd64.tar.gz"
      sha256 "334202859f8f723ac4f08edd44f067435c18c368b31535cdbf1465f8af1f3a41"

      def install
        bin.install "get-jwt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbirks/get-jwt/releases/download/v0.1.1/get-jwt_0.1.1_darwin_arm64.tar.gz"
      sha256 "8d6d54b93b252c94b76abb54e27d8555fcc5619bc695e6bff69076f4abbfbe2d"

      def install
        bin.install "get-jwt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbirks/get-jwt/releases/download/v0.1.1/get-jwt_0.1.1_linux_arm64.tar.gz"
      sha256 "1b4fc90491fb2eb1418b635735c0f7c040f6ca3ffda312548043d1a485c5528b"

      def install
        bin.install "get-jwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbirks/get-jwt/releases/download/v0.1.1/get-jwt_0.1.1_linux_amd64.tar.gz"
      sha256 "9ea7d62599ae210dddd6f02fb59a70168eec6f829a959f4cf30fbd5cbe421ed8"

      def install
        bin.install "get-jwt"
      end
    end
  end
end
